### ISSUE TITLE
Plugin Development using Additional Application

### ISSUE THREAD

**Issue by tanh609** [ynput/ayon-applications#27]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

I'm currently in the process of developing a plugin for Storyboard Pro (SBP). When I add SBP as an Additional Application and launch AYON in dev mode, the launcher seem to not aware of the SBP plugin that I've created and uploaded to the server. 

My current work around is to edit "applications.json" and "settings.py" in the Application's server folder to make SBP one of the default Application. Then the development workflow work as expected. 

### Expected Behavior:

When using the AYON launcher to launch an Additional Application with in development plugins, it will use the development code. 

### Version

1.0.0

### What platform you are running on?

Windows, Linux / Ubuntu

### Steps To Reproduce:

1. Upload A barebone version of SBP Plugin to AYON server
2. Setup a DEV bundle with SBP and specify a local path for the plugin
3. Add Storyboard Pro as and Additional Application.
4. Launch SBP using AYON launcher

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

**Comment by tanh609** [comment]
Additionally, the name and ICON for storyboard pro has disappeared. 

![image](https://github.com/user-attachments/assets/66c4722a-5566-4045-bf06-97f48d69afdf)

**Comment by tanh609** [comment]
I've just realized that Application v1.0.0 also requires editing the constants.py in both the client and server folder.

**Comment by iLLiCiTiT** [comment]
Hello, if I understand correctly, the issue is that you can't use applications from dev settings? That is actually possible now since 1.0.0, because applications are not defined via attributes, but via settings, so dev applications can be relected in dev mode.

> I've just realized that Application v1.0.0 also requires editing the constants.py in both the client and server folder to make SBP pro appears properly in the Application Launcher.

That is true only for icon, which already has dedicated issue https://github.com/ynput/ayon-applications/issues/21 , label can be defined in settings.

Please confirm if I got the issue correctly. If only remaining issue is that icon can't be defined other way that via constants, then this issue can be closed.

**Comment by tanh609** [comment]
Hullo @iLLiCiTiT, sorry for the late reply. I can confirm that this issue has been resolved. I'll close this issue.
